mode: single_cdr

sampling:
  sample_structure: true
  sample_sequence: false
  num_samples: 5

dataset:
  test:
    class: SAbDab
    mmap_dir: ./datasets/sabdab
    cdr_type: L_CDR3
    specify_index: ./datasets/sabdab/L_CDR3/train.txt

dataloader:
  shuffle: false
  num_workers: 4
  batch_size: 32
